site_name: PHP Chess
site_url: https://chesslablab.github.io/php-chess/
theme:
  name: mkdocs
nav:
  - Getting Started: getting-started.md
  - Formats: formats.md
  - Heuristics: heuristics.md
  - Tutor: tutor.md
  - Play Chess: play-chess.md
  - PGN Parsing: pgn-parsing.md
